### ISSUE TITLE
Stacktrace during the run

### ISSUE THREAD

**Issue by USSX-Hares** [Kevin-Lee/maven2sbt#299]
# Bug

# Summary

# Project Details
Version: 1.4.0, 1.3.0
Scala Version: n/a
Java Version: n/a

**Additional context**

# Description
**Describe the bug**

**To Reproduce**
1. Clean installation using the GraalVM
2. Run

## Actual:
```
java.lang.RuntimeException: Unsupported scope: import
	at scala.sys.package$.error(package.scala:27)
	at maven2sbt.core.Scope$.parseUnsafe$$anonfun$1(Scope.scala:89)
	at scala.util.Either.fold(Either.scala:190)
	at maven2sbt.core.Scope$.parseUnsafe(Scope.scala:89)
	at maven2sbt.core.DependencyPlus.from$$anonfun$7$$anonfun$6(DependencyPlus.scala:106)
	at scala.Option.fold(Option.scala:263)
	at maven2sbt.core.DependencyPlus.from$$anonfun$1(DependencyPlus.scala:106)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:99)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:86)
	at scala.xml.NodeSeq.map(NodeSeq.scala:51)
	at maven2sbt.core.DependencyPlus.from(DependencyPlus.scala:110)
	at maven2sbt.core.DependencyPlus.from$(DependencyPlus.scala:14)
	at maven2sbt.core.Dependency$.from(Dependency.scala:9)
	at maven2sbt.core.LibsPlus.from$$anonfun$1(LibsPlus.scala:30)
	at scala.collection.StrictOptimizedIterableOps.flatMap(StrictOptimizedIterableOps.scala:117)
	at scala.collection.StrictOptimizedIterableOps.flatMap$(StrictOptimizedIterableOps.scala:104)
	at scala.xml.NodeSeq.flatMap(NodeSeq.scala:51)
	at maven2sbt.core.LibsPlus.from(LibsPlus.scala:31)
	at maven2sbt.core.LibsPlus.from$(LibsPlus.scala:14)
	at maven2sbt.core.Libs$.from(Libs.scala:8)
	at maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbt$$anonfun$6$$anonfun$5$$anonfun$4$$anonfun$3$$anonfun$1(Maven2Sbt.scala:61)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbt$$anonfun$20$$anonfun$19$$anonfun$18$$anonfun$17(Maven2Sbt.scala:94)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbt$$anonfun$21$$anonfun$20$$anonfun$19(Maven2Sbt.scala:94)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbt$$anonfun$22$$anonfun$21(Maven2Sbt.scala:94)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbt$$anonfun$1(Maven2Sbt.scala:94)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbt(Maven2Sbt.scala:94)
	at map @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbtFromPomFile$$anonfun$8$$anonfun$4(Maven2Sbt.scala:107)
	at liftF @ effectie.cats.EitherTSupport$PartiallyAppliedEitherTRightEffectOf$.apply$extension(EitherTSupport.scala:58)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbtFromPomFile(Maven2Sbt.scala:107)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbtFromPomFile(Maven2Sbt.scala:107)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbtFromPomFile(Maven2Sbt.scala:107)
	at run @ com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at bracket @ maven2sbt.cli.Maven2SbtApp$.runApp$$anonfun$18$$anonfun$14(Maven2SbtApp.scala:59)
	at map @ maven2sbt.cli.Maven2SbtApp$.runApp$$anonfun$18$$anonfun$14(Maven2SbtApp.scala:61)
	at flatMap @ maven2sbt.cli.Maven2SbtApp$.runApp$$anonfun$2(Maven2SbtApp.scala:61)
	at flatMap @ maven2sbt.cli.Maven2SbtApp$.runApp(Maven2SbtApp.scala:61)
	at flatMap @ maven2sbt.cli.MainIo.run$$anonfun$1(MainIo.scala:42)
```

**Comment by Kevin-Lee** [comment]
@USSX-Hares Could you please share the exact command you ran when you had that error?

**Comment by Kevin-Lee** [comment]
Also could you share the `pom.xml` that causes that error after removing all sensitive data (e.g. password, username, any proprietary stuff, etc.)?

**Comment by USSX-Hares** [comment]
@Kevin-Lee, `pom.xml` from Jenkins 'empty-plugin' template:
https://www.jenkins.io/doc/developer/tutorial/create/
```
mvn -U archetype:generate -Dfilter="io.jenkins.archetypes:"
```

[pom.xml.tar.gz](https://github.com/Kevin-Lee/maven2sbt/files/8994199/pom.xml.tar.gz)

Command: 
```
/home/testpresso/opt/maven2sbt-cli/maven2sbt file -s 2.13.8 ~/pom.xml --overwrite
```

**Comment by USSX-Hares** [comment]
Also, @Kevin-Lee, you can DM me on Discord: Hares#9301

**Comment by Kevin-Lee** [comment]
@USSX-Hares Thanks! I'll have a look.

**Comment by Kevin-Lee** [comment]
Oh so it's about importing a pom file. Unfortunately, this is not one of supported features but I'll consider adding it.
