### ISSUE TITLE
Issue with Unsupported scope...

### ISSUE THREAD

**Issue by aocalderon** [kevin-lee/maven2sbt#339]
# Bug
java.lang.RuntimeException: Unsupported scope: ${dependency.scope}

# Summary
program throws a Runtime Exception

# Project Details
Version: 1.4.0
Scala Version: 2.11.12
Java Version: 1.8

# Description
**Describe the bug**
program throws java.lang.RuntimeException: Unsupported scope: ${dependency.scope} when try to convert this [pom](https://raw.githubusercontent.com/zishanfu/GeoSparkSim/dev/pom.xml)

**To Reproduce**
1. With this [pom](https://raw.githubusercontent.com/zishanfu/GeoSparkSim/dev/pom.xml)
2. Run this command `maven2sbt file -s 2.11.12 pom.xml`
3. See error `
java.lang.RuntimeException: Unsupported scope: ${dependency.scope}
	at scala.sys.package$.error(package.scala:27)
	at maven2sbt.core.Scope$.parseUnsafe$$anonfun$1(Scope.scala:89)
	at scala.util.Either.fold(Either.scala:190)
	at maven2sbt.core.Scope$.parseUnsafe(Scope.scala:89)
	at maven2sbt.core.DependencyPlus.from$$anonfun$7$$anonfun$6(DependencyPlus.scala:106)
	at scala.Option.fold(Option.scala:263)
	at maven2sbt.core.DependencyPlus.from$$anonfun$1(DependencyPlus.scala:106)
	at scala.collection.StrictOptimizedIterableOps.map(StrictOptimizedIterableOps.scala:99)
	at scala.collection.StrictOptimizedIterableOps.map$(StrictOptimizedIterableOps.scala:86)
	at scala.xml.NodeSeq.map(NodeSeq.scala:51)
	at maven2sbt.core.DependencyPlus.from(DependencyPlus.scala:110)
	at maven2sbt.core.DependencyPlus.from$(DependencyPlus.scala:14)
	at maven2sbt.core.Dependency$.from(Dependency.scala:9)
	at maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbt$$anonfun$8$$anonfun$7$$anonfun$6$$anonfun$5$$anonfun$3$$anonfun$2$$anonfun$1(Maven2Sbt.scala:63)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbt$$anonfun$18$$anonfun$17$$anonfun$16$$anonfun$15$$anonfun$13$$anonfun$12(Maven2Sbt.scala:94)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbt$$anonfun$19$$anonfun$18$$anonfun$17$$anonfun$16$$anonfun$14(Maven2Sbt.scala:94)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbt$$anonfun$20$$anonfun$19$$anonfun$18$$anonfun$17(Maven2Sbt.scala:94)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbt$$anonfun$21$$anonfun$20$$anonfun$19(Maven2Sbt.scala:94)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbt$$anonfun$22$$anonfun$21(Maven2Sbt.scala:94)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbt$$anonfun$1(Maven2Sbt.scala:94)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbt(Maven2Sbt.scala:94)
	at map @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbtFromPomFile$$anonfun$8$$anonfun$4(Maven2Sbt.scala:107)
	at liftF @ effectie.cats.EitherTSupport$PartiallyAppliedEitherTRightEffectOf$.apply$extension(EitherTSupport.scala:58)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbtFromPomFile(Maven2Sbt.scala:107)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbtFromPomFile(Maven2Sbt.scala:107)
	at flatMap @ maven2sbt.core.Maven2Sbt$Maven2SbtF.buildSbtFromPomFile(Maven2Sbt.scala:107)
	at run @ com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at bracket @ maven2sbt.cli.Maven2SbtApp$.runApp$$anonfun$18$$anonfun$14(Maven2SbtApp.scala:59)
	at map @ maven2sbt.cli.Maven2SbtApp$.runApp$$anonfun$18$$anonfun$14(Maven2SbtApp.scala:61)
	at flatMap @ maven2sbt.cli.Maven2SbtApp$.runApp$$anonfun$2(Maven2SbtApp.scala:61)
`

**Expected behavior**

a build.sbt file

---
Below this line is for the project maintainer so don't worry about it.

---

# Possible Cause
# Cause

# Possible Solution
# Solution

**Comment by kevin-lee** [comment]
@aocalderon Thanks, Andres, for reporting this.
I've got what it is from your report and will fix it this week.

**Comment by kevin-lee** [comment]
@aocalderon The fix is on the way.

I also found that the option you used wasn't sufficient for your `pom.xml`, so once it's released, please use it with `-b scala.compat.version` option as well.
e.g.)
```shell
maven2sbt file -s 2.11.12 -b scala.compat.version pom.xml
```

**Comment by kevin-lee** [comment]
@aocalderon It's been released. Please install it again to get the latest version.
https://maven2sbt.kevinly.dev/docs/cli/get-cli

**Comment by aocalderon** [comment]
Works like a charm! Thank you very much!

**Comment by kevin-lee** [comment]
@aocalderon Thanks for using it and feedback!
